package com.netplus.qrengine.utils

const val TOKEN =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9ybUlkIjoiYzIzMDY1MTctNmE5Mi0xMWVhLTk1N2MtZjIzYzkyOWIwMDU3IiwidGVybWluYWxJZCI6IjIxMDFKQTI2IiwiYnVzaW5lc3NOYW1lIjoib2xhbWlkZUB3ZWJtYWxsLm5nIiwibWlkIjoiMCIsInBhcnRuZXJJZCI6bnVsbCwiZG9tYWlucyI6WyJuZXRwb3MiXSwicm9sZXMiOlsiYWRtaW4iXSwiaXNzIjoic3Rvcm06YWNjb3VudHMiLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNjY3MjU3NDI3LCJleHAiOjE2OTg3OTM0Mjd9.5pI7PDOYGB6FdfbZNs7R6ewlMWFlw95eSZM6H6Gpl0g"
const val QR_AUTH_BASE_URL = "https://getqr.netpluspay.com"
const val TRANSACTIONS_BASE_URL = "https://device.netpluspay.com"
const val MERCHANTS_BASE_URL = "https://contactless.netpluspay.com/user/get-partner-user"
const val QR_ENGINE_BASE_URL = "https://tally.netpluspay.com/api/transactions"
const val STORE_PARTNER_KEYS = "https://tally.netpluspay.com/api/storePartnerSecret"
const val GET_PARTNER_KEYS = "https://tally.netpluspay.com/api/getPartnerSecret"
const val API_KEY = "27403342c95d1d83a40c0a8523803ec1518e2e5d6edd64b6296a81e8f94b1091"
const val CHECK_OUT_URL = "https://paytally.netpluspay.com/v2/checkout"
const val CHECK_OUT_PAY_URL = "https://paytally.netpluspay.com/v2/pay"
const val MERCHANT_ID = "MID63dbdc67badab"
const val CURRENCY_TYPE = "NGN"
const val HTML_FILE_PATH = "file:///android_asset/3ds_pay.html"
const val WEB_RESPONSE_SUCCESS_CODE = "00"
const val WEB_RESPONSE_FAILURE_CODE_1 = "80"
const val WEB_RESPONSE_FAILURE_CODE_2 = "90"
const val TOKENIZING_CARD_LOADING_TEXT = "Tokenizing card..."